### ISSUE TITLE
Unexpected Keyword Argument 'action_factory' after Rasa_Core 0.10.0 -> 0.11.0

### ISSUE THREAD

**Issue by MxmRz** [schul-cloud/cui#22]
After updating the core to 0.11.0 and changing import-statements in both `rasa-core/account.py` and `rasa-core/server.py` (according to the migration guide: https://rasa.com/docs/core/migrations/) the chatbot cant load any agent model: 

> rasa-core_1          | 2019-01-05 15:43:44 WARNING  server  - Failed to load any agent model. Running Rasa Core server with out loaded model now. load() got an unexpected keyword argument 'action_factory'

The load-function using action_factory can be found in `rasa-core/server.py` in line 152:

> return Agent.load(model_directory, interpreter,
                          tracker_store=tracker_store,
                          action_factory=action_factory)

The migration guide does not mention the action_factory at all and the chatbot does not work with this problem.
